steps:
  - name: ubuntu
    args: ["sed", "-i", "s/__TAG_NAME__/$TAG_NAME/", "nanonauts/index.html"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./nanonauts/", "gs://gfx.goldsolutions.co.nz/"]
